text = """
You see two rooms...
One to the right, one to the left.
You have a torch in your right hand...
"""

[[choice]]
text = "Go right"
to = "right_torch"

[[choice]]
text = "Go left"
to = "left_torch"

[[choice]]
text = "Light up the torch"
to = "center_lit_torch"
