text = """
You are standing in an empty room, with a torch
in your right hand...
"""

[[choice]]
text = "Go back"
to = "left_torch"

[[choice]]
text = "Light up the torch"
to = "secret_room_lit_torch"
